using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;

using M42.Data;
using M42.Data.Models;

namespace M42.Data.Initializer
{
    public static class SportsCardInitializer
    {
        public static void Seed(M42Context m42)
        {
            SeedManufacturers(m42);
            SeedBrands(m42);

            SeedReleases(m42);
            SeedBaseballReleases(m42);
            SeedFootballReleases(m42);
            SeedBasketballReleases(m42);

            SeedSets(m42);
            SeedCards(m42);
            SeedContainers(m42);
            SeedInventory(m42);
        }      

        private static void SeedBaseballReleases(M42Context context)
        {
            string baseballReleasesFilename = System.IO.Path.Combine(Constants.SportsCardFolder, "BaseballReleases.csv");

            string[] lines = System.IO.File.ReadAllLines(baseballReleasesFilename);

            foreach (string line in lines)
            {
                string[] values = line.Split(',');

                int year = Convert.ToInt32(values[0]);
                string manufacturerIdentifier = values[1];
                string brandIdentifier = values[2];
                string leagueIdentifier = values[3];
                int numCards = Convert.ToInt32(values[4]);

                DataService.AddRelease(context, year, manufacturerIdentifier, brandIdentifier, leagueIdentifier, numCards);
            }
        }
        private static void SeedFootballReleases(M42Context context)
        {
            string footballReleasesFilename = System.IO.Path.Combine(Constants.SportsCardFolder, "FootballReleases.csv");

            string[] lines = System.IO.File.ReadAllLines(footballReleasesFilename);

            foreach (string line in lines)
            {
                string[] values = line.Split(',');

                int year = Convert.ToInt32(values[0]);
                string manufacturerIdentifier = values[1];
                string brandIdentifier = values[2];
                string leagueIdentifier = values[3];
                int numCards = Convert.ToInt32(values[4]);

                DataService.AddRelease(context, year, manufacturerIdentifier, brandIdentifier, leagueIdentifier, numCards);
            }
        }
        private static void SeedBasketballReleases(M42Context context)
        {
            string basketballReleasesFilename = System.IO.Path.Combine(Constants.SportsCardFolder, "BasketballReleases.csv");

            string[] lines = System.IO.File.ReadAllLines(basketballReleasesFilename);

            foreach (string line in lines)
            {
                string[] values = line.Split(',');

                int year = Convert.ToInt32(values[0]);
                string manufacturerIdentifier = values[1];
                string brandIdentifier = values[2];
                string leagueIdentifier = values[3];
                int numCards = Convert.ToInt32(values[4]);

                DataService.AddRelease(context, year, manufacturerIdentifier, brandIdentifier, leagueIdentifier, numCards);
            }
        }
        private static void SeedManufacturers(M42Context context)
        {
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "The Topps Company", Identifier = "TheToppsCompany", YearEstablished = 1950, ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Pinnacle", Identifier = "Pinnacle", YearEstablished = 1989, YearEnded = 1998, ActiveFlag = false } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Proset", Identifier = "Proset", YearEstablished = 1989, YearEnded = 1994, ActiveFlag = false } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Upper Deck", Identifier = "UpperDeck", YearEstablished = 1989, ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Donruss", Identifier = "Donruss", YearEstablished = 1954, YearEnded = 1998, ActiveFlag = false } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Panini", Identifier = "Panini", YearEstablished = 1961, ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Leaf", Identifier = "Leaf", YearEstablished = 1948, YearEnded = 1998, ActiveFlag = false } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Bowman", Identifier = "Bowman", YearEstablished = 1948, YearEnded = 1956, ActiveFlag = false } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Playoff", Identifier = "Playoff", YearEstablished = 1970, YearEnded = 2001, ActiveFlag = false } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Philadelphia", Identifier = "Philadelphia", YearEstablished = 1964, YearEnded = 1968, ActiveFlag = false } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Action Packed", Identifier = "ActionPacked", YearEstablished = 1988, YearEnded = 1997, ActiveFlag = false } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Fleer", Identifier = "Fleer", YearEstablished = 1885, YearEnded = 2006, ActiveFlag = false } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Donruss Playoff", Identifier = "DonrussPlayoff", YearEstablished = 1999, YearEnded = 2009, ActiveFlag = false } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Press Pass", Identifier = "PressPass", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Sage", Identifier = "Sage", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Wildcard", Identifier = "Wildcard", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Collectors Edge", Identifier = "CollectorsEdge", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Pacific", Identifier = "Pacific", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "MAXX", Identifier = "MAXX", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Hoops", Identifier = "Hoops", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Skybox", Identifier = "Skybox", YearEstablished = 1990, YearEnded = 1995, ActiveFlag = false } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Pro Line", Identifier = "ProLine", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "O-Pee-Chee", Identifier = "OPeeChee", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "AW Sports", Identifier = "AWSports", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Dogtags", Identifier = "Dogtags", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "Enor", Identifier = "Enor", ActiveFlag = true } });
            context.Manufacturers.Add(new Manufacturer { Organization = new Organization { Name = "The Score Board", Identifier = "TheScoreBoard", ActiveFlag = true } });

            context.SaveChanges();
        }
        private static void SeedBrands(M42Context context)
        {
            context.Brands.Add(new Brand { Name = "Topps", Identifier = "Topps" });
            context.Brands.Add(new Brand { Name = "Bowman", Identifier = "Bowman" });
            context.Brands.Add(new Brand { Name = "Donruss", Identifier = "Donruss" });
            context.Brands.Add(new Brand { Name = "Leaf", Identifier = "Leaf" });
            context.Brands.Add(new Brand { Name = "Score", Identifier = "Score" });
            context.Brands.Add(new Brand { Name = "Playoff", Identifier = "Playoff" });
            context.Brands.Add(new Brand { Name = "Upper Deck", Identifier = "UpperDeck" });
            context.Brands.Add(new Brand { Name = "Topps Finest", Identifier = "ToppsFinest" });
            context.Brands.Add(new Brand { Name = "Topps Heritage", Identifier = "ToppsHeritage" });
            context.Brands.Add(new Brand { Name = "Topps Chrome", Identifier = "ToppsChrome" });
            context.Brands.Add(new Brand { Name = "Bowman Chrome", Identifier = "BowmanChrome" });
            context.Brands.Add(new Brand { Name = "Bowman Sterling", Identifier = "BowmanSterling" });
            context.Brands.Add(new Brand { Name = "Bazooka", Identifier = "Bazooka" });
            context.Brands.Add(new Brand { Name = "SP", Identifier = "SP" });
            context.Brands.Add(new Brand { Name = "SPx", Identifier = "SPx" });
            context.Brands.Add(new Brand { Name = "Wonder Bread", Identifier = "WonderBread" });
            context.Brands.Add(new Brand { Name = "Fleer", Identifier = "Fleer" });
            context.Brands.Add(new Brand { Name = "Ultra", Identifier = "Ultra" });
            context.Brands.Add(new Brand { Name = "Flair", Identifier = "Flair" });
            context.Brands.Add(new Brand { Name = "Action Packed", Identifier = "ActionPacked" });
            context.Brands.Add(new Brand { Name = "SP Authentic", Identifier = "SPAuthentic" });
            context.Brands.Add(new Brand { Name = "Crown Royale", Identifier = "CrownRoyale" });
            context.Brands.Add(new Brand { Name = "Epix", Identifier = "Epix" });
            context.Brands.Add(new Brand { Name = "Hoops", Identifier = "Hoops" });
            context.Brands.Add(new Brand { Name = "Maxx", Identifier = "Maxx" });
            context.Brands.Add(new Brand { Name = "Philadelphia", Identifier = "Philadelphia" });
            context.Brands.Add(new Brand { Name = "Post", Identifier = "Post" });
            context.Brands.Add(new Brand { Name = "Pacific", Identifier = "Pacific" });
            context.Brands.Add(new Brand { Name = "Proset", Identifier = "Proset" });
            context.Brands.Add(new Brand { Name = "Pro Line", Identifier = "ProLine" });
            context.Brands.Add(new Brand { Name = "Kellogs", Identifier = "Kellogs" });
            context.Brands.Add(new Brand { Name = "Press Pass", Identifier = "PressPass" });
            context.Brands.Add(new Brand { Name = "Press Pass Legends", Identifier = "PressPassLegends" });
            context.Brands.Add(new Brand { Name = "Press Pass SE", Identifier = "PressPassSE" });
            context.Brands.Add(new Brand { Name = "Sports Illustrated", Identifier = "SportsIllustrated" });
            context.Brands.Add(new Brand { Name = "Stadium Club", Identifier = "StadiumClub" });
            context.Brands.Add(new Brand { Name = "Dominos", Identifier = "Dominos" });
            context.Brands.Add(new Brand { Name = "Leaf Limited", Identifier = "LeafLimited" });
            context.Brands.Add(new Brand { Name = "Leaf Certified Materials", Identifier = "LeafCertifiedMaterials" });
            context.Brands.Add(new Brand { Name = "Donruss Classics", Identifier = "DonrussClassics" });
            context.Brands.Add(new Brand { Name = "Topps Total", Identifier = "ToppsTotal" });
            context.Brands.Add(new Brand { Name = "Topps Triple Threads", Identifier = "ToppsTripleThreads" });
            context.Brands.Add(new Brand { Name = "Topps Turkey Red", Identifier = "ToppsTurkeyRed" });
            context.Brands.Add(new Brand { Name = "Sage Hit", Identifier = "SageHit" });
            context.Brands.Add(new Brand { Name = "Skybox", Identifier = "Skybox" });
            context.Brands.Add(new Brand { Name = "Topps Inception", Identifier = "ToppsInception" });
            context.Brands.Add(new Brand { Name = "Topps Rising Rookies", Identifier = "ToppsRisingRookies" });
            context.Brands.Add(new Brand { Name = "Topps Prime", Identifier = "ToppsPrime" });
            context.Brands.Add(new Brand { Name = "Topps Magic", Identifier = "ToppsMagic" });
            context.Brands.Add(new Brand { Name = "Topps Legends", Identifier = "ToppsLegends" });
            context.Brands.Add(new Brand { Name = "Topps Draft Picks and Prospects", Identifier = "ToppsDraftPicksandProspects" });
            context.Brands.Add(new Brand { Name = "Topps Platinum", Identifier = "ToppsPlatinum" });
            context.Brands.Add(new Brand { Name = "Playoff National Treasures", Identifier = "PlayoffNationalTreasures" });
            context.Brands.Add(new Brand { Name = "Playoff Prestige", Identifier = "PlayoffPrestige" });
            context.Brands.Add(new Brand { Name = "Fleer Tradition", Identifier = "FleerTradition" });
            context.Brands.Add(new Brand { Name = "Donruss Elite", Identifier = "DonrussElite" });
            context.Brands.Add(new Brand { Name = "Donruss Gridiron Gear", Identifier = "DonrussGridironGear" });
            context.Brands.Add(new Brand { Name = "Donruss Threads", Identifier = "DonrussThreads" });
            context.Brands.Add(new Brand { Name = "Playoff Absolute Memorabilia", Identifier = "PlayoffAbsoluteMemorabilia" });
            context.Brands.Add(new Brand { Name = "Topps Supreme", Identifier = "ToppsSupreme" });
            context.Brands.Add(new Brand { Name = "Kaybee", Identifier = "Kaybee" });
            context.Brands.Add(new Brand { Name = "Woolworth", Identifier = "Woolworth" });
            context.Brands.Add(new Brand { Name = "Leaf Rookies and Stars", Identifier = "LeafRookiesandStars" });
            context.Brands.Add(new Brand { Name = "Leaf Rookies and Stars Longevity", Identifier = "LeafRookiesandStarsLongevity" });
            context.Brands.Add(new Brand { Name = "Mayo Cut Plug", Identifier = "MayoCutPlug" });
            context.Brands.Add(new Brand { Name = "National Chicle", Identifier = "NationalChicle" });
            context.Brands.Add(new Brand { Name = "Topps Unrivaled", Identifier = "ToppsUnrivaled" });
            context.Brands.Add(new Brand { Name = "Upper Deck Artifacts", Identifier = "UpperDeckArtifacts" });
            context.Brands.Add(new Brand { Name = "Upper Deck Exquisite", Identifier = "UpperDeckExquisite" });
            context.Brands.Add(new Brand { Name = "Upper Deck Legends", Identifier = "UpperDeckLegends" });
            context.Brands.Add(new Brand { Name = "Upper Deck Rookie Premiere", Identifier = "UpperDeckRookiePremiere" });
            context.Brands.Add(new Brand { Name = "Upper Deck Rookie Materials", Identifier = "UpperDeckRookieMaterials" });
            context.Brands.Add(new Brand { Name = "Upper Deck Rookie Debut", Identifier = "UpperDeckRookieDebut" });
            context.Brands.Add(new Brand { Name = "Upper Deck Masterpieces", Identifier = "UpperDeckMasterpieces" });
            context.Brands.Add(new Brand { Name = "Bowmans Best", Identifier = "BowmansBest" });
            context.Brands.Add(new Brand { Name = "Donruss Throwback Threads", Identifier = "DonrussThrowbackThreads" });
            context.Brands.Add(new Brand { Name = "Playoff Contenders", Identifier = "PlayoffContenders" });
            context.Brands.Add(new Brand { Name = "Sage Game Exclusives", Identifier = "SageGameExclusives" });
            context.Brands.Add(new Brand { Name = "Upper Deck Icons", Identifier = "UpperDeckIcons" });
            context.Brands.Add(new Brand { Name = "Topps TX Exclusives", Identifier = "ToppsTXExclusives" });
            context.Brands.Add(new Brand { Name = "Wildcard", Identifier = "Wildcard" });
            context.Brands.Add(new Brand { Name = "Topps Rookie Progression", Identifier = "ToppsRookieProgression" });
            context.Brands.Add(new Brand { Name = "Upper Deck Football Heroes", Identifier = "UpperDeckFootballHeroes" });
            context.Brands.Add(new Brand { Name = "Upper Deck First Edition", Identifier = "UpperDeckFirstEdition" });
            context.Brands.Add(new Brand { Name = "SP Threads", Identifier = "SPThreads" });
            context.Brands.Add(new Brand { Name = "Upper Deck Collectors Choice", Identifier = "UpperDeckCollectorsChoice" });
            context.Brands.Add(new Brand { Name = "Topps Tribute", Identifier = "ToppsTribute" });
            context.Brands.Add(new Brand { Name = "Topps Stickers", Identifier = "ToppsStickers" });
            context.Brands.Add(new Brand { Name = "Topps Small", Identifier = "ToppsSmall" });
            context.Brands.Add(new Brand { Name = "Skybox Impact", Identifier = "SkyboxImpact" });
            context.Brands.Add(new Brand { Name = "Skybox Premium", Identifier = "SkyboxPremium" });
            context.Brands.Add(new Brand { Name = "Upper Deck Victory", Identifier = "UpperDeckVictory" });
            context.Brands.Add(new Brand { Name = "Topps Gallery", Identifier = "ToppsGallery" });
            context.Brands.Add(new Brand { Name = "Fleer Inscribed", Identifier = "FleerInscribed" });
            context.Brands.Add(new Brand { Name = "Fleer Platinum", Identifier = "FleerPlatinum" });
            context.Brands.Add(new Brand { Name = "Upper Deck Pros and Prospects", Identifier = "UpperDeckProsandProspects" });
            context.Brands.Add(new Brand { Name = "Pacific Revolution", Identifier = "PacificRevolution" });
            context.Brands.Add(new Brand { Name = "Pacific Invincible", Identifier = "PacificInvincible" });
            context.Brands.Add(new Brand { Name = "Pacific Private Stock", Identifier = "PacificPrivateStock" });
            context.Brands.Add(new Brand { Name = "Panini Stickers", Identifier = "PaniniStickers" });
            context.Brands.Add(new Brand { Name = "Panini Gold Standard", Identifier = "PaniniGoldStandard" });
            context.Brands.Add(new Brand { Name = "Panini Plates & Patches", Identifier = "PaniniPlates&Patches" });
            context.Brands.Add(new Brand { Name = "Upper Deck Draft Edition", Identifier = "UpperDeckDraftEdition" });
            context.Brands.Add(new Brand { Name = "Collectors Edge Odyssey", Identifier = "CollectorsEdgeOdyssey" });
            context.Brands.Add(new Brand { Name = "Collectors Edge Boss Squad", Identifier = "CollectorsEdgeBossSquad" });
            context.Brands.Add(new Brand { Name = "O-Pee-Chee", Identifier = "OPeeChee" });
            context.Brands.Add(new Brand { Name = "Stars and Stripes", Identifier = "StarsandStripes" });
            context.Brands.Add(new Brand { Name = "Fleer Award Winners", Identifier = "FleerAwardWinners" });
            context.Brands.Add(new Brand { Name = "Aspire", Identifier = "Aspire" });
            context.Brands.Add(new Brand { Name = "Upper Deck Heroes", Identifier = "UpperDeckHeroes" });
            context.Brands.Add(new Brand { Name = "SP Rookie Edition", Identifier = "SPRookieEdition" });
            context.Brands.Add(new Brand { Name = "Upper Deck ESPN", Identifier = "UpperDeckESPN" });
            context.Brands.Add(new Brand { Name = "Upper Deck Kickoff", Identifier = "UpperDeckKickoff" });
            context.Brands.Add(new Brand { Name = "SP Signature", Identifier = "SPSignature" });
            context.Brands.Add(new Brand { Name = "Upper Deck Sweet Spot", Identifier = "UpperDeckSweetSpot" });
            context.Brands.Add(new Brand { Name = "Topps Archives", Identifier = "ToppsArchives" });
            context.Brands.Add(new Brand { Name = "Collectors Edge", Identifier = "CollectorsEdge" });
            context.Brands.Add(new Brand { Name = "AW Sports", Identifier = "AWSports" });
            context.Brands.Add(new Brand { Name = "Dogtags", Identifier = "Dogtags" });
            context.Brands.Add(new Brand { Name = "Swell", Identifier = "Swell" });
            context.Brands.Add(new Brand { Name = "Hall of Fame", Identifier = "HallofFame" });
            context.Brands.Add(new Brand { Name = "SP Signature Edition", Identifier = "SPSignatureEdition" });
            context.Brands.Add(new Brand { Name = "Collectors Edge T3", Identifier = "CollectorsEdgeT3" });
            context.Brands.Add(new Brand { Name = "Adrenaline", Identifier = "Adrenaline" });
            context.Brands.Add(new Brand { Name = "Playoff Hogg Heaven", Identifier = "PlayoffHoggHeaven" });
            context.Brands.Add(new Brand { Name = "Playoff Prime Signatures", Identifier = "PlayoffPrimeSignatures" });
            context.Brands.Add(new Brand { Name = "Topps All Time Fan Favorites", Identifier = "ToppsAllTimeFanFavorites" });
            context.Brands.Add(new Brand { Name = "Fleer Hot Prospects", Identifier = "FleerHotProspects" });
            context.Brands.Add(new Brand { Name = "Beckett", Identifier = "Beckett" });
            context.Brands.Add(new Brand { Name = "Topps Gilt Edge", Identifier = "ToppsGiltEdge" });
            context.Brands.Add(new Brand { Name = "Leaf Quantum", Identifier = "LeafQuantum" });
            context.Brands.Add(new Brand { Name = "Fleer Mystique", Identifier = "FleerMystique" });
            context.Brands.Add(new Brand { Name = "All Sport", Identifier = "AllSport" });
            context.Brands.Add(new Brand { Name = "Allen & Ginter", Identifier = "Allen&Ginter" });
            context.Brands.Add(new Brand { Name = "Topps USFL", Identifier = "ToppsUSFL" });
            context.Brands.Add(new Brand { Name = "Pinnacle", Identifier = "Pinnacle" });
            context.Brands.Add(new Brand { Name = "Proset Platinum", Identifier = "ProsetPlatinum" });
            context.Brands.Add(new Brand { Name = "Profiles", Identifier = "Profiles" });
            context.Brands.Add(new Brand { Name = "Pacific Prisms", Identifier = "PacificPrisms" });
            context.Brands.Add(new Brand { Name = "Felt Backs", Identifier = "FeltBacks" });
            context.Brands.Add(new Brand { Name = "Magic", Identifier = "Magic" });
            context.Brands.Add(new Brand { Name = "All-American", Identifier = "AllAmerican" });
            context.Brands.Add(new Brand { Name = "Tier One", Identifier = "TierOne" });
            context.Brands.Add(new Brand { Name = "Prime Signatures", Identifier = "PrimeSignatures" });
            context.Brands.Add(new Brand { Name = "Prism", Identifier = "Prism" });
            context.Brands.Add(new Brand { Name = "Classics", Identifier = "Classics" });
            context.Brands.Add(new Brand { Name = "Strata", Identifier = "ToppsStrata" });
            context.Brands.Add(new Brand { Name = "Classics", Identifier = "PaniniClassics" });
            context.Brands.Add(new Brand { Name = "Certified", Identifier = "PaniniCertified" });
            context.Brands.Add(new Brand { Name = "Contenders", Identifier = "PaniniContenders" });

            context.SaveChanges();
        }
        private static void SeedReleases(M42Context context)
        {
            DataService.AddRelease(context, 1948, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 1948, "Leaf", "Leaf", "NFL");
            DataService.AddRelease(context, 1949, "Leaf", "Leaf", "NFL");
            DataService.AddRelease(context, 1950, "TheToppsCompany", "FeltBacks", "NFL");
            DataService.AddRelease(context, 1950, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 1951, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 1951, "TheToppsCompany", "Magic", "NFL");
            DataService.AddRelease(context, 1952, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 1953, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 1954, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 1955, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 1955, "TheToppsCompany", "AllAmerican", "NFL");
            DataService.AddRelease(context, 1956, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1957, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1957, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1958, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1958, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1959, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1960, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1960, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1961, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1961, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1962, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1962, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1963, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1963, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1964, "Philadelphia", "Philadelphia", "NFL");
            DataService.AddRelease(context, 1964, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1965, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1965, "Philadelphia", "Philadelphia", "NFL");
            DataService.AddRelease(context, 1966, "Philadelphia", "Philadelphia", "NFL");
            DataService.AddRelease(context, 1966, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1967, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1967, "Philadelphia", "Philadelphia", "NFL");
            DataService.AddRelease(context, 1968, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1969, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1970, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1970, "TheToppsCompany", "Kellogs", "NFL");
            DataService.AddRelease(context, 1971, "OPeeChee", "OPeeChee", "CFL");
            DataService.AddRelease(context, 1971, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1971, "TheToppsCompany", "Topps", "NBA");
            DataService.AddRelease(context, 1971, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1972, "OPeeChee", "OPeeChee", "CFL");
            DataService.AddRelease(context, 1972, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1973, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1974, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1975, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1975, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1975, "TheToppsCompany", "WonderBread", "NFL");
            DataService.AddRelease(context, 1976, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1976, "TheToppsCompany", "WonderBread", "NFL");
            DataService.AddRelease(context, 1977, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1977, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1978, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1978, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1979, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1979, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1979, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1980, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1980, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1981, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1981, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1981, "TheToppsCompany", "ToppsStickers", "NFL");
            DataService.AddRelease(context, 1982, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1982, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1982, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1983, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1983, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1984, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1984, "TheToppsCompany", "ToppsStickers", "NFL");
            DataService.AddRelease(context, 1984, "TheToppsCompany", "ToppsUSFL", "USFL");
            DataService.AddRelease(context, 1985, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1985, "Donruss", "Donruss", "MLB");
            DataService.AddRelease(context, 1985, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1985, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1985, "TheToppsCompany", "ToppsStickers", "NFL");
            DataService.AddRelease(context, 1985, "TheToppsCompany", "ToppsUSFL", "USFL");
            DataService.AddRelease(context, 1986, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1986, "TheToppsCompany", "ToppsSmall", "MLB");
            DataService.AddRelease(context, 1986, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1986, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1987, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1987, "Donruss", "Donruss", "MLB");
            DataService.AddRelease(context, 1987, "Fleer", "FleerAwardWinners", "MLB");
            DataService.AddRelease(context, 1987, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1987, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1987, "TheToppsCompany", "ToppsSmall", "NFL");
            DataService.AddRelease(context, 1988, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1988, "Donruss", "Donruss", "MLB");
            DataService.AddRelease(context, 1988, "Leaf", "Leaf", "MLB");
            DataService.AddRelease(context, 1988, "Pacific", "Pacific", "MLB");
            DataService.AddRelease(context, 1988, "Pinnacle", "Score", "MLB");
            DataService.AddRelease(context, 1988, "Panini", "PaniniStickers", "MLB");
            DataService.AddRelease(context, 1988, "MAXX", "Maxx", "NASCAR");
            DataService.AddRelease(context, 1988, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1989, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1989, "Donruss", "Donruss", "MLB");
            DataService.AddRelease(context, 1989, "UpperDeck", "UpperDeck", "MLB");
            DataService.AddRelease(context, 1989, "Fleer", "Fleer", "MLB");
            DataService.AddRelease(context, 1989, "Pinnacle", "Score", "MLB");
            DataService.AddRelease(context, 1989, "TheToppsCompany", "ToppsSmall", "MLB");
            DataService.AddRelease(context, 1989, "MAXX", "Maxx", "NASCAR");
            DataService.AddRelease(context, 1989, "Hoops", "Hoops", "NBA");
            DataService.AddRelease(context, 1989, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1989, "ActionPacked", "ActionPacked", "NFL");
            DataService.AddRelease(context, 1989, "Proset", "Proset", "NFL");
            DataService.AddRelease(context, 1989, "Pinnacle", "Score", "NFL");
            DataService.AddRelease(context, 1990, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 1990, "TheToppsCompany", "Bowman", "MLB");
            DataService.AddRelease(context, 1990, "Donruss", "Donruss", "MLB");
            DataService.AddRelease(context, 1990, "UpperDeck", "UpperDeck", "MLB");
            DataService.AddRelease(context, 1990, "Fleer", "Fleer", "MLB");
            DataService.AddRelease(context, 1990, "TheToppsCompany", "Post", "MLB");
            DataService.AddRelease(context, 1990, "Pinnacle", "Score", "MLB");
            DataService.AddRelease(context, 1990, "TheToppsCompany", "Kaybee", "MLB");
            DataService.AddRelease(context, 1990, "TheToppsCompany", "Woolworth", "MLB");
            DataService.AddRelease(context, 1990, "TheToppsCompany", "ToppsSmall", "MLB");
            DataService.AddRelease(context, 1990, "Fleer", "FleerAwardWinners", "MLB");
            DataService.AddRelease(context, 1990, "Skybox", "Skybox", "NBA");
            DataService.AddRelease(context, 1990, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1990, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1990, "ActionPacked", "ActionPacked", "NFL");
            DataService.AddRelease(context, 1990, "Proset", "Proset", "NFL");
            DataService.AddRelease(context, 1990, "Pinnacle", "Score", "NFL");
            DataService.AddRelease(context, 1990, "Panini", "PaniniStickers", "NFL");
            DataService.AddRelease(context, 1990, "Fleer", "StarsandStripes", "NFL");
            DataService.AddRelease(context, 1990, "TheToppsCompany", "Swell", "NFL");
            DataService.AddRelease(context, 1991, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 1991, "Pinnacle", "Pinnacle", "NFL");
            DataService.AddRelease(context, 1991, "Proset", "ProsetPlatinum", "NFL");
            DataService.AddRelease(context, 1991, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1991, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 1991, "UpperDeck", "SP", "NFL");
            DataService.AddRelease(context, 1991, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1991, "Fleer", "Ultra", "NFL");
            DataService.AddRelease(context, 1991, "ActionPacked", "ActionPacked", "NFL");
            DataService.AddRelease(context, 1991, "Pacific", "Pacific", "NFL");
            DataService.AddRelease(context, 1991, "Proset", "Proset", "NFL");
            DataService.AddRelease(context, 1991, "Pinnacle", "Score", "NFL");
            DataService.AddRelease(context, 1991, "ProLine", "ProLine", "NFL");
            DataService.AddRelease(context, 1991, "TheToppsCompany", "StadiumClub", "NFL");
            DataService.AddRelease(context, 1991, "UpperDeck", "Dominos", "NFL");
            DataService.AddRelease(context, 1991, "Wildcard", "Wildcard", "NFL");
            DataService.AddRelease(context, 1991, "Fleer", "StarsandStripes", "NFL");
            DataService.AddRelease(context, 1991, "Enor", "HallofFame", "NFL");
            DataService.AddRelease(context, 1992, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1992, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 1992, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1992, "ActionPacked", "ActionPacked", "NFL");
            DataService.AddRelease(context, 1992, "Proset", "Proset", "NFL");
            DataService.AddRelease(context, 1992, "ProLine", "ProLine", "NFL");
            DataService.AddRelease(context, 1992, "TheToppsCompany", "StadiumClub", "NFL");
            DataService.AddRelease(context, 1992, "Skybox", "Skybox", "NFL");
            DataService.AddRelease(context, 1992, "Wildcard", "Wildcard", "NFL");
            DataService.AddRelease(context, 1992, "AWSports", "AWSports", "NFL");
            DataService.AddRelease(context, 1992, "Dogtags", "Dogtags", "NFL");
            DataService.AddRelease(context, 1992, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 1992, "Pacific", "Pacific", "NFL");
            DataService.AddRelease(context, 1992, "Pinnacle", "Pinnacle", "NFL");
            DataService.AddRelease(context, 1992, "ProLine", "Profiles", "NFL");
            DataService.AddRelease(context, 1992, "Pinnacle", "Score", "NFL");
            DataService.AddRelease(context, 1992, "Fleer", "Ultra", "NFL");
            DataService.AddRelease(context, 1992, "CollectorsEdge", "CollectorsEdge", "NFL");
            DataService.AddRelease(context, 1992, "Playoff", "Playoff", "NFL");
            DataService.AddRelease(context, 1993, "Playoff", "PlayoffContenders", "NFL");
            DataService.AddRelease(context, 1993, "Pinnacle", "Score", "NFL");
            DataService.AddRelease(context, 1993, "Proset", "Proset", "NFL");
            DataService.AddRelease(context, 1993, "Fleer", "Ultra", "NFL");
            DataService.AddRelease(context, 1993, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 1993, "Wildcard", "Wildcard", "NFL");
            DataService.AddRelease(context, 1993, "CollectorsEdge", "CollectorsEdge", "NFL");
            DataService.AddRelease(context, 1993, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1993, "Pacific", "Pacific", "NFL");
            DataService.AddRelease(context, 1993, "Pacific", "PacificPrisms", "NFL");
            DataService.AddRelease(context, 1993, "Pinnacle", "Pinnacle", "NFL");
            DataService.AddRelease(context, 1993, "ActionPacked", "ActionPacked", "NFL");
            DataService.AddRelease(context, 1993, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 1993, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1993, "Playoff", "Playoff", "NFL");
            DataService.AddRelease(context, 1993, "ProLine", "ProLine", "NFL");
            DataService.AddRelease(context, 1993, "TheToppsCompany", "StadiumClub", "NFL");
            DataService.AddRelease(context, 1994, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1994, "Playoff", "Playoff", "NFL");
            DataService.AddRelease(context, 1994, "Fleer", "Ultra", "NFL");
            DataService.AddRelease(context, 1994, "ActionPacked", "ActionPacked", "NFL");
            DataService.AddRelease(context, 1994, "UpperDeck", "UpperDeckCollectorsChoice", "NFL");
            DataService.AddRelease(context, 1994, "CollectorsEdge", "CollectorsEdge", "NFL");
            DataService.AddRelease(context, 1994, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 1994, "TheToppsCompany", "ToppsFinest", "NFL");
            DataService.AddRelease(context, 1994, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 1994, "Pacific", "Pacific", "NFL");
            DataService.AddRelease(context, 1994, "Pinnacle", "Pinnacle", "NFL");
            DataService.AddRelease(context, 1994, "TheToppsCompany", "StadiumClub", "NFL");
            DataService.AddRelease(context, 1994, "Pinnacle", "Score", "NFL");
            DataService.AddRelease(context, 1994, "Playoff", "Playoff", "NFL");
            DataService.AddRelease(context, 1995, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1995, "UpperDeck", "SP", "NFL");
            DataService.AddRelease(context, 1995, "Pacific", "Pacific", "NFL");
            DataService.AddRelease(context, 1995, "Pinnacle", "Score", "NFL");
            DataService.AddRelease(context, 1995, "Skybox", "SkyboxImpact", "NFL");
            DataService.AddRelease(context, 1995, "CollectorsEdge", "CollectorsEdge", "NFL");
            DataService.AddRelease(context, 1996, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1996, "Playoff", "Playoff", "NFL");
            DataService.AddRelease(context, 1996, "DonrussPlayoff", "Playoff", "NFL");
            DataService.AddRelease(context, 1996, "Pacific", "Pacific", "NFL");
            DataService.AddRelease(context, 1996, "TheToppsCompany", "StadiumClub", "NFL");
            DataService.AddRelease(context, 1996, "UpperDeck", "UpperDeckCollectorsChoice", "NFL");
            DataService.AddRelease(context, 1996, "TheToppsCompany", "ToppsGiltEdge", "NFL");
            DataService.AddRelease(context, 1997, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1997, "Playoff", "Playoff", "NFL");
            DataService.AddRelease(context, 1997, "Pacific", "Pacific", "NFL");
            DataService.AddRelease(context, 1997, "CollectorsEdge", "UpperDeckCollectorsChoice", "NFL");
            DataService.AddRelease(context, 1998, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1998, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 1998, "Pacific", "PacificRevolution", "NFL");
            DataService.AddRelease(context, 1999, "PressPass", "PressPass", "NCAAF");
            DataService.AddRelease(context, 1999, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 1999, "DonrussPlayoff", "Score", "NFL");
            DataService.AddRelease(context, 1999, "Fleer", "SportsIllustrated", "NFL");
            DataService.AddRelease(context, 1999, "TheToppsCompany", "BowmansBest", "NFL");
            DataService.AddRelease(context, 1999, "Skybox", "SkyboxPremium", "NFL");
            DataService.AddRelease(context, 1999, "CollectorsEdge", "CollectorsEdge", "NFL");
            DataService.AddRelease(context, 1999, "UpperDeck", "SPSignatureEdition", "NFL");
            DataService.AddRelease(context, 1999, "Fleer", "FleerMystique", "NFL");
            DataService.AddRelease(context, 2000, "PressPass", "PressPass", "NCAAF");
            DataService.AddRelease(context, 2000, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2000, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 2000, "DonrussPlayoff", "Donruss", "NFL");
            DataService.AddRelease(context, 2000, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 2000, "Fleer", "Fleer", "NFL");
            DataService.AddRelease(context, 2000, "Pacific", "Pacific", "NFL");
            DataService.AddRelease(context, 2000, "DonrussPlayoff", "Score", "NFL");
            DataService.AddRelease(context, 2000, "TheToppsCompany", "StadiumClub", "NFL");
            DataService.AddRelease(context, 2000, "DonrussPlayoff", "LeafRookiesandStars", "NFL");
            DataService.AddRelease(context, 2000, "UpperDeck", "UpperDeckLegends", "NFL");
            DataService.AddRelease(context, 2000, "TheToppsCompany", "BowmansBest", "NFL");
            DataService.AddRelease(context, 2000, "UpperDeck", "UpperDeckVictory", "NFL");
            DataService.AddRelease(context, 2000, "CollectorsEdge", "CollectorsEdgeOdyssey", "NFL");
            DataService.AddRelease(context, 2000, "CollectorsEdge", "CollectorsEdge", "NFL");
            DataService.AddRelease(context, 2000, "CollectorsEdge", "CollectorsEdgeT3", "NFL");
            DataService.AddRelease(context, 2000, "DonrussPlayoff", "LeafQuantum", "NFL");
            DataService.AddRelease(context, 2001, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2001, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 2001, "TheToppsCompany", "ToppsHeritage", "NFL");
            DataService.AddRelease(context, 2001, "Pacific", "Pacific", "NFL");
            DataService.AddRelease(context, 2001, "DonrussPlayoff", "Score", "NFL");
            DataService.AddRelease(context, 2001, "TheToppsCompany", "StadiumClub", "NFL");
            DataService.AddRelease(context, 2001, "UpperDeck", "UpperDeckLegends", "NFL");
            DataService.AddRelease(context, 2001, "UpperDeck", "UpperDeckVictory", "NFL");
            DataService.AddRelease(context, 2001, "TheToppsCompany", "ToppsGallery", "NFL");
            DataService.AddRelease(context, 2001, "Pacific", "PacificInvincible", "NFL");
            DataService.AddRelease(context, 2001, "TheToppsCompany", "ToppsArchives", "NFL");
            DataService.AddRelease(context, 2002, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2002, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 2002, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 2002, "TheToppsCompany", "ToppsHeritage", "NFL");
            DataService.AddRelease(context, 2002, "UpperDeck", "SPAuthentic", "NFL");
            DataService.AddRelease(context, 2002, "DonrussPlayoff", "Score", "NFL");
            DataService.AddRelease(context, 2002, "DonrussPlayoff", "LeafCertifiedMaterials", "NFL");
            DataService.AddRelease(context, 2002, "DonrussPlayoff", "PlayoffPrestige", "NFL");
            DataService.AddRelease(context, 2002, "DonrussPlayoff", "LeafRookiesandStars", "NFL");
            DataService.AddRelease(context, 2002, "Pacific", "PacificPrivateStock", "NFL");
            DataService.AddRelease(context, 2002, "Pacific", "Adrenaline", "NFL");
            DataService.AddRelease(context, 2003, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2003, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 2003, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 2003, "TheToppsCompany", "BowmanChrome", "NFL");
            DataService.AddRelease(context, 2003, "UpperDeck", "SPAuthentic", "NFL");
            DataService.AddRelease(context, 2003, "DonrussPlayoff", "Score", "NFL");
            DataService.AddRelease(context, 2003, "DonrussPlayoff", "DonrussClassics", "NFL");
            DataService.AddRelease(context, 2003, "Fleer", "FleerTradition", "NFL");
            DataService.AddRelease(context, 2003, "DonrussPlayoff", "DonrussElite", "NFL");
            DataService.AddRelease(context, 2003, "DonrussPlayoff", "LeafRookiesandStars", "NFL");
            DataService.AddRelease(context, 2003, "Fleer", "FleerPlatinum", "NFL");
            DataService.AddRelease(context, 2003, "UpperDeck", "UpperDeckProsandProspects", "NFL");
            DataService.AddRelease(context, 2004, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2004, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 2004, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 2004, "TheToppsCompany", "ToppsFinest", "NFL");
            DataService.AddRelease(context, 2004, "TheToppsCompany", "ToppsChrome", "NFL");
            DataService.AddRelease(context, 2004, "TheToppsCompany", "BowmanChrome", "NFL");
            DataService.AddRelease(context, 2004, "TheToppsCompany", "Bazooka", "NFL");
            DataService.AddRelease(context, 2004, "Fleer", "Ultra", "NFL");
            DataService.AddRelease(context, 2004, "UpperDeck", "SPAuthentic", "NFL");
            DataService.AddRelease(context, 2004, "DonrussPlayoff", "LeafCertifiedMaterials", "NFL");
            DataService.AddRelease(context, 2004, "DonrussPlayoff", "DonrussClassics", "NFL");
            DataService.AddRelease(context, 2004, "TheToppsCompany", "ToppsTotal", "NFL");
            DataService.AddRelease(context, 2004, "TheToppsCompany", "ToppsDraftPicksandProspects", "NFL");
            DataService.AddRelease(context, 2004, "Fleer", "FleerTradition", "NFL");
            DataService.AddRelease(context, 2004, "DonrussPlayoff", "DonrussElite", "NFL");
            DataService.AddRelease(context, 2004, "DonrussPlayoff", "PlayoffAbsoluteMemorabilia", "NFL");
            DataService.AddRelease(context, 2004, "DonrussPlayoff", "LeafRookiesandStars", "NFL");
            DataService.AddRelease(context, 2004, "UpperDeck", "UpperDeckLegends", "NFL");
            DataService.AddRelease(context, 2004, "Fleer", "FleerInscribed", "NFL");
            DataService.AddRelease(context, 2004, "Fleer", "FleerPlatinum", "NFL");
            DataService.AddRelease(context, 2004, "UpperDeck", "UpperDeckSweetSpot", "NFL");
            DataService.AddRelease(context, 2004, "DonrussPlayoff", "PlayoffHoggHeaven", "NFL");
            DataService.AddRelease(context, 2004, "DonrussPlayoff", "PlayoffPrimeSignatures", "NFL");
            DataService.AddRelease(context, 2004, "TheToppsCompany", "ToppsAllTimeFanFavorites", "NFL");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "ToppsTotal", "NBA");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 2005, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "ToppsFinest", "NFL");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "ToppsHeritage", "NFL");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "ToppsChrome", "NFL");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "BowmanChrome", "NFL");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "Bazooka", "NFL");
            DataService.AddRelease(context, 2005, "UpperDeck", "SPx", "NFL");
            DataService.AddRelease(context, 2005, "Fleer", "Ultra", "NFL");
            DataService.AddRelease(context, 2005, "UpperDeck", "SPAuthentic", "NFL");
            DataService.AddRelease(context, 2005, "DonrussPlayoff", "Score", "NFL");
            DataService.AddRelease(context, 2005, "DonrussPlayoff", "LeafLimited", "NFL");
            DataService.AddRelease(context, 2005, "DonrussPlayoff", "LeafCertifiedMaterials", "NFL");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "ToppsTotal", "NFL");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "ToppsTurkeyRed", "NFL");
            DataService.AddRelease(context, 2005, "DonrussPlayoff", "PlayoffPrestige", "NFL");
            DataService.AddRelease(context, 2005, "DonrussPlayoff", "DonrussElite", "NFL");
            DataService.AddRelease(context, 2005, "DonrussPlayoff", "PlayoffAbsoluteMemorabilia", "NFL");
            DataService.AddRelease(context, 2005, "DonrussPlayoff", "LeafRookiesandStars", "NFL");
            DataService.AddRelease(context, 2005, "DonrussPlayoff", "LeafRookiesandStarsLongevity", "NFL");
            DataService.AddRelease(context, 2005, "UpperDeck", "UpperDeckLegends", "NFL");
            DataService.AddRelease(context, 2005, "UpperDeck", "UpperDeckRookiePremiere", "NFL");
            DataService.AddRelease(context, 2005, "UpperDeck", "UpperDeckRookieMaterials", "NFL");
            DataService.AddRelease(context, 2005, "DonrussPlayoff", "DonrussThrowbackThreads", "NFL");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "ToppsTribute", "NFL");
            DataService.AddRelease(context, 2005, "UpperDeck", "UpperDeckESPN", "NFL");
            DataService.AddRelease(context, 2005, "UpperDeck", "UpperDeckKickoff", "NFL");
            DataService.AddRelease(context, 2005, "TheToppsCompany", "Beckett", "NFL");
            DataService.AddRelease(context, 2005, "UpperDeck", "UpperDeckVictory", "NHL");
            DataService.AddRelease(context, 2006, "PressPass", "PressPass", "NCAAF");
            DataService.AddRelease(context, 2006, "PressPass", "PressPassLegends", "NCAAF");
            DataService.AddRelease(context, 2006, "PressPass", "PressPassSE", "NCAAF");
            DataService.AddRelease(context, 2006, "Sage", "SageHit", "NCAAF");
            DataService.AddRelease(context, 2006, "Sage", "SageGameExclusives", "NCAAF");
            DataService.AddRelease(context, 2006, "Sage", "Aspire", "NCAAF");
            DataService.AddRelease(context, 2006, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2006, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 2006, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 2006, "TheToppsCompany", "ToppsFinest", "NFL");
            DataService.AddRelease(context, 2006, "TheToppsCompany", "ToppsHeritage", "NFL");
            DataService.AddRelease(context, 2006, "TheToppsCompany", "ToppsChrome", "NFL");
            DataService.AddRelease(context, 2006, "TheToppsCompany", "BowmanChrome", "NFL");
            DataService.AddRelease(context, 2006, "TheToppsCompany", "BowmanSterling", "NFL");
            DataService.AddRelease(context, 2006, "UpperDeck", "SPx", "NFL");
            DataService.AddRelease(context, 2006, "UpperDeck", "Fleer", "NFL");
            DataService.AddRelease(context, 2006, "UpperDeck", "Ultra", "NFL");
            DataService.AddRelease(context, 2006, "UpperDeck", "Flair", "NFL");
            DataService.AddRelease(context, 2006, "UpperDeck", "SPAuthentic", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "Score", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "LeafLimited", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "LeafCertifiedMaterials", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "DonrussClassics", "NFL");
            DataService.AddRelease(context, 2006, "TheToppsCompany", "ToppsTotal", "NFL");
            DataService.AddRelease(context, 2006, "TheToppsCompany", "ToppsTripleThreads", "NFL");
            DataService.AddRelease(context, 2006, "TheToppsCompany", "ToppsTurkeyRed", "NFL");
            DataService.AddRelease(context, 2006, "TheToppsCompany", "ToppsDraftPicksandProspects", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "PlayoffNationalTreasures", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "PlayoffPrestige", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "DonrussElite", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "DonrussGridironGear", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "DonrussThreads", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "PlayoffAbsoluteMemorabilia", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "LeafRookiesandStars", "NFL");
            DataService.AddRelease(context, 2006, "UpperDeck", "UpperDeckExquisite", "NFL");
            DataService.AddRelease(context, 2006, "UpperDeck", "UpperDeckLegends", "NFL");
            DataService.AddRelease(context, 2006, "UpperDeck", "UpperDeckRookieDebut", "NFL");
            DataService.AddRelease(context, 2006, "DonrussPlayoff", "PlayoffContenders", "NFL");
            DataService.AddRelease(context, 2006, "UpperDeck", "UpperDeckSweetSpot", "NFL");
            DataService.AddRelease(context, 2006, "UpperDeck", "FleerHotProspects", "NFL");
            DataService.AddRelease(context, 2007, "PressPass", "PressPassLegends", "NCAABB");
            DataService.AddRelease(context, 2007, "PressPass", "PressPass", "NCAAF");
            DataService.AddRelease(context, 2007, "PressPass", "PressPassLegends", "NCAAF");
            DataService.AddRelease(context, 2007, "PressPass", "PressPassSE", "NCAAF");
            DataService.AddRelease(context, 2007, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2007, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 2007, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 2007, "TheToppsCompany", "ToppsChrome", "NFL");
            DataService.AddRelease(context, 2007, "TheToppsCompany", "BowmanChrome", "NFL");
            DataService.AddRelease(context, 2007, "TheToppsCompany", "BowmanSterling", "NFL");
            DataService.AddRelease(context, 2007, "UpperDeck", "SPx", "NFL");
            DataService.AddRelease(context, 2007, "UpperDeck", "Ultra", "NFL");
            DataService.AddRelease(context, 2007, "UpperDeck", "SPAuthentic", "NFL");
            DataService.AddRelease(context, 2007, "DonrussPlayoff", "Score", "NFL");
            DataService.AddRelease(context, 2007, "DonrussPlayoff", "LeafCertifiedMaterials", "NFL");
            DataService.AddRelease(context, 2007, "DonrussPlayoff", "DonrussClassics", "NFL");
            DataService.AddRelease(context, 2007, "TheToppsCompany", "ToppsTotal", "NFL");
            DataService.AddRelease(context, 2007, "TheToppsCompany", "ToppsDraftPicksandProspects", "NFL");
            DataService.AddRelease(context, 2007, "DonrussPlayoff", "PlayoffNationalTreasures", "NFL");
            DataService.AddRelease(context, 2007, "DonrussPlayoff", "PlayoffPrestige", "NFL");
            DataService.AddRelease(context, 2007, "DonrussPlayoff", "DonrussElite", "NFL");
            DataService.AddRelease(context, 2007, "DonrussPlayoff", "DonrussGridironGear", "NFL");
            DataService.AddRelease(context, 2007, "DonrussPlayoff", "DonrussThreads", "NFL");
            DataService.AddRelease(context, 2007, "DonrussPlayoff", "PlayoffAbsoluteMemorabilia", "NFL");
            DataService.AddRelease(context, 2007, "DonrussPlayoff", "LeafRookiesandStarsLongevity", "NFL");
            DataService.AddRelease(context, 2007, "UpperDeck", "UpperDeckArtifacts", "NFL");
            DataService.AddRelease(context, 2007, "TheToppsCompany", "ToppsTXExclusives", "NFL");
            DataService.AddRelease(context, 2007, "UpperDeck", "UpperDeckFirstEdition", "NFL");
            DataService.AddRelease(context, 2008, "PressPass", "PressPassLegends", "NCAAF");
            DataService.AddRelease(context, 2008, "PressPass", "PressPassSE", "NCAAF");
            DataService.AddRelease(context, 2008, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2008, "DonrussPlayoff", "Playoff", "NFL");
            DataService.AddRelease(context, 2008, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 2008, "TheToppsCompany", "BowmanChrome", "NFL");
            DataService.AddRelease(context, 2008, "UpperDeck", "SPAuthentic", "NFL");
            DataService.AddRelease(context, 2008, "DonrussPlayoff", "Score", "NFL");
            DataService.AddRelease(context, 2008, "DonrussPlayoff", "LeafLimited", "NFL");
            DataService.AddRelease(context, 2008, "DonrussPlayoff", "LeafCertifiedMaterials", "NFL");
            DataService.AddRelease(context, 2008, "DonrussPlayoff", "DonrussClassics", "NFL");
            DataService.AddRelease(context, 2008, "DonrussPlayoff", "PlayoffPrestige", "NFL");
            DataService.AddRelease(context, 2008, "DonrussPlayoff", "DonrussGridironGear", "NFL");
            DataService.AddRelease(context, 2008, "DonrussPlayoff", "PlayoffAbsoluteMemorabilia", "NFL");
            DataService.AddRelease(context, 2008, "DonrussPlayoff", "LeafRookiesandStars", "NFL");
            DataService.AddRelease(context, 2008, "TheToppsCompany", "MayoCutPlug", "NFL");
            DataService.AddRelease(context, 2008, "UpperDeck", "UpperDeckMasterpieces", "NFL");
            DataService.AddRelease(context, 2008, "UpperDeck", "UpperDeckIcons", "NFL");
            DataService.AddRelease(context, 2008, "TheToppsCompany", "ToppsRookieProgression", "NFL");
            DataService.AddRelease(context, 2008, "UpperDeck", "UpperDeckFirstEdition", "NFL");
            DataService.AddRelease(context, 2008, "UpperDeck", "UpperDeckDraftEdition", "NFL");
            DataService.AddRelease(context, 2008, "UpperDeck", "UpperDeckHeroes", "NFL");
            DataService.AddRelease(context, 2008, "UpperDeck", "SPRookieEdition", "NFL");
            DataService.AddRelease(context, 2009, "PressPass", "PressPass", "NCAAF");
            DataService.AddRelease(context, 2009, "PressPass", "PressPassLegends", "NCAAF");
            DataService.AddRelease(context, 2009, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2009, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 2009, "UpperDeck", "SP", "NFL");
            DataService.AddRelease(context, 2009, "UpperDeck", "SPx", "NFL");
            DataService.AddRelease(context, 2009, "UpperDeck", "SPAuthentic", "NFL");
            DataService.AddRelease(context, 2009, "TheToppsCompany", "Philadelphia", "NFL");
            DataService.AddRelease(context, 2009, "DonrussPlayoff", "Score", "NFL");
            DataService.AddRelease(context, 2009, "DonrussPlayoff", "LeafLimited", "NFL");
            DataService.AddRelease(context, 2009, "DonrussPlayoff", "DonrussClassics", "NFL");
            DataService.AddRelease(context, 2009, "DonrussPlayoff", "PlayoffPrestige", "NFL");
            DataService.AddRelease(context, 2009, "DonrussPlayoff", "DonrussThreads", "NFL");
            DataService.AddRelease(context, 2009, "DonrussPlayoff", "LeafRookiesandStars", "NFL");
            DataService.AddRelease(context, 2009, "TheToppsCompany", "MayoCutPlug", "NFL");
            DataService.AddRelease(context, 2009, "TheToppsCompany", "NationalChicle", "NFL");
            DataService.AddRelease(context, 2009, "UpperDeck", "UpperDeckIcons", "NFL");
            DataService.AddRelease(context, 2009, "UpperDeck", "UpperDeckFootballHeroes", "NFL");
            DataService.AddRelease(context, 2009, "UpperDeck", "UpperDeckFirstEdition", "NFL");
            DataService.AddRelease(context, 2009, "UpperDeck", "SPThreads", "NFL");
            DataService.AddRelease(context, 2009, "UpperDeck", "UpperDeckDraftEdition", "NFL");
            DataService.AddRelease(context, 2009, "UpperDeck", "SPSignature", "NFL");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "Bowman", "MLB");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "ToppsChrome", "MLB");
            DataService.AddRelease(context, 2010, "PressPass", "PressPass", "NCAAF");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2010, "UpperDeck", "UpperDeck", "NFL");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "ToppsFinest", "NFL");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "ToppsChrome", "NFL");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "BowmanSterling", "NFL");
            DataService.AddRelease(context, 2010, "Panini", "Epix", "NFL");
            DataService.AddRelease(context, 2010, "DonrussPlayoff", "Score", "NFL");
            DataService.AddRelease(context, 2010, "Panini", "LeafLimited", "NFL");
            DataService.AddRelease(context, 2010, "DonrussPlayoff", "LeafCertifiedMaterials", "NFL");
            DataService.AddRelease(context, 2010, "DonrussPlayoff", "DonrussClassics", "NFL");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "ToppsTripleThreads", "NFL");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "ToppsMagic", "NFL");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "ToppsPlatinum", "NFL");
            DataService.AddRelease(context, 2010, "DonrussPlayoff", "PlayoffNationalTreasures", "NFL");
            DataService.AddRelease(context, 2010, "Panini", "PlayoffPrestige", "NFL");
            DataService.AddRelease(context, 2010, "DonrussPlayoff", "DonrussElite", "NFL");
            DataService.AddRelease(context, 2010, "DonrussPlayoff", "PlayoffAbsoluteMemorabilia", "NFL");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "ToppsSupreme", "NFL");
            DataService.AddRelease(context, 2010, "Panini", "LeafRookiesandStars", "NFL");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "ToppsUnrivaled", "NFL");
            DataService.AddRelease(context, 2010, "Panini", "PaniniPlates&Patches", "NFL");
            DataService.AddRelease(context, 2011, "PressPass", "PressPass", "NCAAF");
            DataService.AddRelease(context, 2011, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2011, "TheToppsCompany", "ToppsChrome", "NFL");
            DataService.AddRelease(context, 2011, "Panini", "CrownRoyale", "NFL");
            DataService.AddRelease(context, 2011, "Panini", "LeafCertifiedMaterials", "NFL");
            DataService.AddRelease(context, 2011, "TheToppsCompany", "ToppsTripleThreads", "NFL");
            DataService.AddRelease(context, 2011, "TheToppsCompany", "ToppsInception", "NFL");
            DataService.AddRelease(context, 2011, "TheToppsCompany", "ToppsRisingRookies", "NFL");
            DataService.AddRelease(context, 2011, "TheToppsCompany", "ToppsPrime", "NFL");
            DataService.AddRelease(context, 2011, "TheToppsCompany", "ToppsLegends", "NFL");
            DataService.AddRelease(context, 2011, "Panini", "PlayoffPrestige", "NFL");
            DataService.AddRelease(context, 2011, "Panini", "PaniniGoldStandard", "NFL");
            DataService.AddRelease(context, 2011, "Panini", "LeafRookiesandStars", "NFL");
            DataService.AddRelease(context, 2011, "Panini", "PlayoffContenders", "NFL");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "Bowman", "MLB");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "TierOne", "MLB");
            DataService.AddRelease(context, 2012, "Sage", "SageHit", "NCAAF");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "ToppsInception", "NFL");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "ToppsTripleThreads", "NFL");
            DataService.AddRelease(context, 2012, "Panini", "PrimeSignatures", "NFL");
            DataService.AddRelease(context, 2012, "Panini", "PlayoffContenders", "NFL");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 2012, "Panini", "CrownRoyale", "NFL");
            DataService.AddRelease(context, 2012, "Panini", "LeafRookiesandStars", "NFL");
            DataService.AddRelease(context, 2012, "Panini", "Epix", "NFL");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "ToppsChrome", "NFL");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "ToppsFinest", "NFL");
            DataService.AddRelease(context, 2012, "Panini", "PlayoffPrestige", "NFL");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "ToppsMagic", "NFL");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "ToppsTribute", "NFL");
            DataService.AddRelease(context, 2013, "TheToppsCompany", "ToppsArchives", "NFL");
            DataService.AddRelease(context, 2013, "TheToppsCompany", "ToppsPrime", "NFL");
            DataService.AddRelease(context, 2013, "TheToppsCompany", "ToppsPlatinum", "NFL");
            DataService.AddRelease(context, 2013, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2013, "TheToppsCompany", "Bowman", "NFL");
            DataService.AddRelease(context, 2013, "TheToppsCompany", "ToppsChrome", "NFL");
            DataService.AddRelease(context, 2013, "TheToppsCompany", "BowmanChrome", "NFL");
            DataService.AddRelease(context, 2013, "TheToppsCompany", "BowmanSterling", "NFL");
            DataService.AddRelease(context, 2016, "TheToppsCompany", "ToppsChrome", "MLB");
            DataService.AddRelease(context, 2016, "TheToppsCompany", "ToppsTribute", "MLB");
            DataService.AddRelease(context, 2016, "TheToppsCompany", "Allen&Ginter", "MLB");
            DataService.AddRelease(context, 2016, "Panini", "Prism", "NFL");
            DataService.AddRelease(context, 2017, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 2017, "Panini", "Classics", "NFL");

            DataService.AddRelease(context, 1988, "MAXX", "Maxx", "NASCAR");
            DataService.AddRelease(context, 1989, "MAXX", "Maxx", "NASCAR");
            DataService.AddRelease(context, 1996, "Playoff", "Playoff", "NFL");
            DataService.AddRelease(context, 2007, "PressPass", "PressPassLegends", "NCAAB");
            DataService.AddRelease(context, 2010, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "PrimeSignatures", "NFL");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "ToppsChrome", "NFL");
            DataService.AddRelease(context, 2012, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2015, "TheToppsCompany", "Topps", "NFL");
            DataService.AddRelease(context, 2015, "TheToppsCompany", "ToppsStrata", "NFL");
            DataService.AddRelease(context, 2016, "Panini", "PaniniCertified", "NFL");
            DataService.AddRelease(context, 2016, "Panini", "PaniniClassics", "NFL");
            DataService.AddRelease(context, 2016, "Panini", "PaniniContenders", "NFL");
            DataService.AddRelease(context, 2016, "Panini", "Playoff", "NFL");
            DataService.AddRelease(context, 2016, "TheToppsCompany", "ToppsChrome", "MLB");
            DataService.AddRelease(context, 2016, "TheToppsCompany", "Topps", "MLB");
            DataService.AddRelease(context, 2017, "TheToppsCompany", "ToppsFinest", "MLB");
            DataService.AddRelease(context, 2017, "TheToppsCompany", "Topps", "MLB");

            context.SaveChanges();
        }
        private static void SeedSets(M42Context context)
        {
            string scriptPath = Path.Combine(Constants.ScriptsFolder, "SeedSets.sql");

            SqlService.ExecuteSqlScript(context, scriptPath);
        }
        private static void SeedCards(M42Context context)
        {
            string scriptPath = Path.Combine(Constants.ScriptsFolder, "SeedCards.sql");

            SqlService.ExecuteSqlScript(context, scriptPath);
        }
        private static void SeedContainers(M42Context context)
        {
            DataService.AddContainer(context, "CollectionSinglesBox", "M42 Collection Box", ContainerType.TopLoaderBox2.Id, Location.SedonaHouse.Id);
            DataService.AddContainer(context, "M42ShopCollectionBox", "M42.Shop Products", ContainerType.TopLoaderBox2.Id, Location.SedonaHouse.Id);
            DataService.AddContainer(context, "StockSinglesBox1", "Stock Singles Box #1", ContainerType.TopLoaderBox2.Id, Location.SedonaHouse.Id);
            DataService.AddContainer(context, "StockSinglesBox2", "Stock Singles Box #2", ContainerType.TopLoaderBox2.Id, Location.SedonaHouse.Id);
            DataService.AddContainer(context, "GradedBox", "Graded Box", ContainerType.TopLoaderBox2.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "Unknown", "Unknown", ContainerType.TopLoaderBox2.Id, Location.SedonaHouse.Id);

            DataService.AddContainer(context, "NFL-RedskinsBinder1", "Redskins Binder #1", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            DataService.AddContainer(context, "NFL-RedskinsBinder2", "Redskins Binder#2", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            DataService.AddContainer(context, "NFL-RedskinsBinder3", "Redskins Binder#3", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            DataService.AddContainer(context, "NFL-CowboysBinder1", "Cowboys Binder #1", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            DataService.AddContainer(context, "NFL-CowboysBinder2", "Cowboys Binder #2", ContainerType.Binder.Id, Location.SedonaHouse.Id);

            DataService.AddContainer(context, "NFL-RookieBinder", "Rookie Card Binder", ContainerType.Binder.Id, Location.SedonaHouse.Id);

            //DataService.AddContainer(context, "NFL-49ersBinder1", "49ers (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-49ersBinder2", "49ers (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BearsBinder1", "Bears (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BearsBinder2", "Bears (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BengalsBinder1", "Bengals (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BengalsBinder2", "Bengals (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BillsBinder1", "Bills (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BillsBinder2", "Bills (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BroncosBinder1", "Broncos (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BroncosBinder2", "Broncos (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BrownsBinder1", "Browns (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BrownsBinder2", "Browns (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BuccanearsBinder1", "Buccanears (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-BuccanearsBinder2", "Buccanears (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-CardinalsBinder1", "Cardinals (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-CardinalsBinder2", "Cardinals (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-ChargersBinder1", "Chargers (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-ChargersBinder2", "Chargers (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-ChiefsBinder1", "Chiefs (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-ChiefsBinder2", "Chiefs (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-ColtsBinder1", "Colts (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-ColtsBinder2", "Colts (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-DolphinsBinder1", "Dolphins (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-DolphinsBinder2", "Dolphins (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-EaglesBinder1", "Eagles (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-EaglesBinder2", "Eagles (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-FalconsBinder1", "Falcons (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-FalconsBinder2", "Falcons (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-GiantsBinder1", "Giants (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-GiantsBinder2", "Giants (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-Jaguars", "Jaguars (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-JetsBinder1", "Jets (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-JetsBinder2", "Jets (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-LionsBinder1", "Lions (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-LionsBinder2", "Lions (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-Oilers", "Oilers (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-PackersBinder1", "Packers (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-PackersBinder2", "Packers (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-Panthers", "Panthers (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-PatriotsBinder1", "Patriots (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-PatriotsBinder2", "Patriots (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-RaidersBinder1", "Raiders (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-RaidersBinder2", "Raiders (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-RamsBinder1", "Rams (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-RamsBinder2", "Rams (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-Ravens", "Ravens", ContainerType.Binder.Id, Location.SedonaHouse.Id);

            //DataService.AddContainer(context, "NFL-SaintsBinder1", "Saints (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-SaintsBinder2", "Saints (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-SeahawksBinder1", "Seahawks (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-SeahawksBinder2", "Seahawks (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-SteelersBinder1", "Steelers (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-SteelersBinder2", "Steelers (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-Texans", "Texans (2002-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-Titans", "Titans (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-VikingsBinder1", "Vikings (1970-1995)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "NFL-VikingsBinder2", "Vikings (1996-present)", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "College Notebook", "NCAA Football", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "College Singles", "", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "Duplicate Singles", "", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "Mixed", "", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "MixedBinder2", "", ContainerType.Binder.Id, Location.SedonaHouse.Id);
            //DataService.AddContainer(context, "MLB", "", ContainerType.Binder.Id, Location.SedonaHouse.Id);

            //DataService.AddContainer(context, "MLB Singles", "", "");
            //DataService.AddContainer(context, "NFL - Redskins DuplicatesBinder2", "", "");
            //DataService.AddContainer(context, "NFL Commons", "", "");
            //DataService.AddContainer(context, "NFL Duplicate Notebooks", "", "");
            //DataService.AddContainer(context, "NFL Duplicate Singles - Top Loaders", "", "");
            //DataService.AddContainer(context, "NFL RC Duplicate Singles - Top Loaders", "", "");
            //DataService.AddContainer(context, "NFL RC Duplicates", "", "");
            //DataService.AddContainer(context, "NFL RC Duplicates Notebook", "", "");
            //DataService.AddContainer(context, "Premium - Collection", "", "");
            //DataService.AddContainer(context, "Premium - College", "", "");
            //DataService.AddContainer(context, "Safe Deposit", "", "");

            context.SaveChanges();
        }
        private static void SeedInventory(M42Context context)
        {
            string scriptPath = Path.Combine(Constants.ScriptsFolder, "SeedCardInventory.sql");

            SqlService.ExecuteSqlScript(context, scriptPath);
        }
    }
}